### ISSUE TITLE
Build procedure

### ISSUE THREAD

**Issue by fcabestre** [toorop/ovh-cli#4]
Would be nice to have a description of the build procedure. I've just cloned your repository, ``go get`` a couple of dependencies, issued a ``go build`` and got: 

```
../govh/cloud/price.go:6:2: cannot find package "github.com/toorop/govh/order" in any of:
	/home/fcabestr/opt/go/src/github.com/toorop/govh/order (from $GOROOT)
	/home/fcabestr/Projets/Go/src/github.com/toorop/govh/order (from $GOPATH)
```
But this is a package I can't get. 
What did I misses ?

**Comment by toorop** [comment]
I'm rewriting the CLI, i expect to have something "buildable" at the end of the week.

**Comment by fcabestre** [comment]
So I've just inadvertently landed in a work in progress :smile:, that's OK.

**Comment by toorop** [comment]
It should work now.

**Comment by fcabestre** [comment]
Great, it works for me !
